# example values

indexing-settings:
  sites:
    - url: http://localhost
      name: Localhost Test Site
#    - url: http://localhost
#      name: Localhost New Test Site
#    - url: https://lenta.ru
#      name: Лента.ру
#    - url: https://skillbox.ru
#      name: Skillbox
#    - url: https://www.playback.ru
#      name: PlayBack.Ru

bot:
  useragent: HintSearchBot/1.0.0
  referrer: https://ya.ru/
  timeout: 150

server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always
  datasource:
    username: sebot
    password: rtnnfhb#13
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    searchengine:
      services:
        IndexingServiceImpl: DEBUG
        SiteIndexer: DEBUG
        PageIndexer: DEBUG
